stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    # params:
    # - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/interim
  feature_eng:
    cmd: python src/feature_eng.py
    deps:
    - data/interim
    - src/feature_eng.py
    # params:
    # - feature_eng.max_features
    outs:
    - data/processed
  model_train:
    cmd: python src/model_train.py
    deps:
    - data/processed
    - src/model_train.py
    # params:
    # - model_train.n_estimators
    # - model_train.random_state
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model_evaluation.py
    metrics:
    - reports/metrics.json
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step